IBEX35_COMPANIES_HISTORIC = {
    "ANA": "Acciona",
    "ANE": "Acciona Energía",
    "ACX": "Acerinox",
    "ACS": "ACS",
    "AENA": "Aena",
    "AMS": "Amadeus",
    "MTS": "ArcelorMittal",
    "SAB": "Banco Sabadell",
    "SAN": "Banco Santander",
    "BKT": "Bankinter",
    "BBVA": "BBVA",
    "CABK": "CaixaBank",
    "CLNX": "Cellnex Telecom",
    "ENG": "Enagás",
    "END": "Endesa",
    "FER": "Ferrovial",
    "FDR": "Fluidra",
    "GRF": "Grifols",
    "IAG": "IAG",
    "IBE": "Iberdrola",
    "ITX": "Inditex",
    "IDR": "Indra",
    "COL": "Inmobiliaria Colonial",
    "LOG": "Logista",
    "MAP": "Mapfre",
    "MRL": "Merlin Properties",
    "NTGY": "Naturgy",
    "PUIG": "Puig",
    "RED": "Redeia",
    "REP": "Repsol",
    "ROVI": "Rovi",
    "SCYR": "Sacyr",
    "SLR": "Solaria",
    "TEF": "Telefónica",
    "UNI": "Unicaja Banco",
    "ABG": "Abengoa",
    "ABE": "Abertis Infraestructuras",
    "ACR": "Aceralia",
    "AGR": "Agromán",
    "AGS": "Aguas de Barcelona",
    "ALM": "Almirall",
    "ALT": "Altadis",
    "AMP": "Amper",
    "A3TV": "Antena 3 TV",
    "LOR": "Arcelor",
    "ARG": "Argentaria",
    "ASL": "Asland",
    "AZC": "Asturiana de Zinc",
    "AUM": "Autopistas del Mare Nostrum",
    "BBV": "Banco Bilbao Vizcaya",
    "CEN": "Banco Central",
    "BCH": "Banco Central Hispano",
    "HIS": "Banco Hispano Americano",
    "POP": "Banco Popular",
    "BTO": "Banesto",
    "BKIA": "Bankia",
    "BME": "Bolsas y Mercados Españoles",
    "CAR": "Carrefour",
    "CEP": "CEPSA",
    "CIE": "CIE Automotive",
    "CIN": "Cintra",
    "CTE": "Continente",
    "ALB": "Corporación Financiera Alba",
    "CTF": "Cortefiel",
    "SEV": "Compañía Sevillana de Electricidad",
    "CRI": "Cristalería Española",
    "DIA": "DIA",
    "DRC": "Dragados",
    "EBA": "Ebro Agrícolas",
    "EBRO": "Ebro Foods",
    "ENC": "ENCE Energía y Celulosa",
    "ARA": "Energía e Industrias Aragonesas",
    "ECR": "Ercros",
    "FAD": "Fadesa",
    "FCC": "FCC",
    "FEC": "Fuerzas Eléctricas de Cataluña",
    "GES": "GESA",
    "MAS": "Grupo MásMóvil",
    "CAN": "Hidrocantábrico",
    "HHU": "Huarte",
    "IBR": "Iberdrola Renovables",
    "IBLA": "Iberia",
    "JAZ": "Jazztel",
    "TL5": "Mediaset España",
    "MVC": "Metrovacesa",
    "TEM": "Telefónica Móviles",
    "NHH": "NH Hotel Group",
    "OHL": "OHL",
    "PHM": "PharmaMar",
    "GPP": "Picking Pack",
    "VDR": "Portland Valderrivas",
    "PRS": "Prisa",
    "PSG": "Prosegur",
    "PRY": "Pryca",
    "PUL": "Puleva",
    "RAD": "Radiotrónica",
    "SAR": "Sarrió",
    "SGRE": "Siemens Gamesa Renewable Energy",
    "SGC": "Sogecable",
    "TRE": "Técnicas Reunidas",
    "TPI": "Telefónica Publicidad e Información",
    "TPZ": "Telepizza",
    "TRR": "Terra Networks",
    "TUB": "Tubacex",
    "URA": "Uralita",
    "UNF": "Unión Fenosa",
    "URB": "Urbis",
    "VIS": "Viscofan",
    "ZOT": "Zardoya Otis",
    "ZEL": "Zeltia",
}

IBEX35_SECTORS_HISTORIC = {
    "ANA": "Industrials",
    "ANE": "Renewables",
    "ACX": "Materials",
    "ACS": "Industrials",
    "AENA": "Industrials",
    "AMS": "Technology",
    "MTS": "Materials",
    "SAB": "Financials",
    "SAN": "Financials",
    "BKT": "Financials",
    "BBVA": "Financials",
    "CABK": "Financials",
    "CLNX": "Telecom",
    "ENG": "Utilities",
    "END": "Energy",
    "FER": "Industrials",
    "FDR": "Industrials",
    "GRF": "Healthcare",
    "IAG": "Airlines",
    "IBE": "Energy",
    "ITX": "Consumer",
    "IDR": "Technology",
    "COL": "RealEstate",
    "LOG": "Logistics",
    "MAP": "Financials",
    "MRL": "RealEstate",
    "NTGY": "Energy",
    "PUIG": "Consumer",
    "RED": "Utilities",
    "REP": "Energy",
    "ROVI": "Healthcare",
    "SCYR": "Industrials",
    "SLR": "Renewables",
    "TEF": "Telecom",
    "UNI": "Financials",
    "ABG": "Industrials",
    "ABE": "Industrials",
    "ACR": "Materials",
    "AGR": "Industrials",
    "AGS": "Utilities",
    "ALM": "Healthcare",
    "ALT": "Consumer",
    "AMP": "Technology",
    "A3TV": "Media",
    "LOR": "Materials",
    "ARG": "Financials",
    "ASL": "Materials",
    "AZC": "Materials",
    "AUM": "Industrials",
    "BBV": "Financials",
    "CEN": "Financials",
    "BCH": "Financials",
    "HIS": "Financials",
    "POP": "Financials",
    "BTO": "Financials",
    "BKIA": "Financials",
    "BME": "Financials",
    "CAR": "Consumer",
    "CEP": "Energy",
    "CIE": "Industrials",
    "CIN": "Industrials",
    "CTE": "Consumer",
    "ALB": "Financials",
    "CTF": "Consumer",
    "SEV": "Utilities",
    "CRI": "Materials",
    "DIA": "Consumer",
    "DRC": "Industrials",
    "EBA": "Consumer",
    "EBRO": "Consumer",
    "ENC": "Materials",
    "ARA": "Materials",
    "ECR": "Materials",
    "FAD": "RealEstate",
    "FCC": "Industrials",
    "FEC": "Utilities",
    "GES": "Utilities",
    "MAS": "Telecom",
    "CAN": "Utilities",
    "HHU": "Industrials",
    "IBR": "Renewables",
    "IBLA": "Airlines",
    "JAZ": "Telecom",
    "TL5": "Media",
    "MVC": "RealEstate",
    "TEM": "Telecom",
    "NHH": "Consumer",
    "OHL": "Industrials",
    "PHM": "Healthcare",
    "GPP": "Technology",
    "VDR": "Materials",
    "PRS": "Media",
    "PSG": "Industrials",
    "PRY": "Consumer",
    "PUL": "Consumer",
    "RAD": "Technology",
    "SAR": "Materials",
    "SGRE": "Renewables",
    "SGC": "Media",
    "TRE": "Industrials",
    "TPI": "Media",
    "TPZ": "Consumer",
    "TRR": "Telecom",
    "TUB": "Materials",
    "URA": "Materials",
    "UNF": "Utilities",
    "URB": "RealEstate",
    "VIS": "Consumer",
    "ZOT": "Industrials",
    "ZEL": "Healthcare",
}

