IBEX35_COMPANIES = {
    "ANA": "Acciona",
    "ANE": "Acciona Energía",
    "ACX": "Acerinox",
    "ACS": "ACS",
    "AENA": "Aena",
    "AMS": "Amadeus",
    "MTS": "ArcelorMittal",
    "SAB": "Banco Sabadell",
    "SAN": "Banco Santander",
    "BKT": "Bankinter",
    "BBVA": "BBVA",
    "CABK": "CaixaBank",
    "CLNX": "Cellnex Telecom",
    "ENG": "Enagás",
    "END": "Endesa",
    "FER": "Ferrovial",
    "FDR": "Fluidra",
    "GRF": "Grifols",
    "IAG": "IAG",
    "IBE": "Iberdrola",
    "ITX": "Inditex",
    "IDR": "Indra",
    "COL": "Inmobiliaria Colonial",
    "LOG": "Logista",
    "MAP": "Mapfre",
    "MRL": "Merlin Properties",
    "NTGY": "Naturgy",
    "PUIG": "Puig",
    "RED": "Redeia",
    "REP": "Repsol",
    "ROVI": "Rovi",
    "SCYR": "Sacyr",
    "SLR": "Solaria",
    "TEF": "Telefónica",
    "UNI": "Unicaja Banco"
}

IBEX35_SECTORS = {
    "ANA": "Industrials",
    "ANE": "Renewables",
    "ACX": "Materials",
    "ACS": "Industrials",
    "AENA": "Industrials",
    "AMS": "Technology",
    "MTS": "Materials",
    "SAB": "Financials",
    "SAN": "Financials",
    "BKT": "Financials",
    "BBVA": "Financials",
    "CABK": "Financials",
    "CLNX": "Telecom",
    "ENG": "Utilities",
    "END": "Energy",
    "FER": "Industrials",
    "FDR": "Industrials",
    "GRF": "Healthcare",
    "IAG": "Airlines",
    "IBE": "Energy",
    "ITX": "Consumer",
    "IDR": "Technology",
    "COL": "RealEstate",
    "LOG": "Logistics",
    "MAP": "Financials",
    "MRL": "RealEstate",
    "NTGY": "Energy",
    "PUIG": "Consumer",
    "RED": "Utilities",
    "REP": "Energy",
    "ROVI": "Healthcare",
    "SCYR": "Industrials",
    "SLR": "Renewables",
    "TEF": "Telecom",
    "UNI": "Financials"
}

TARGET_DOMAINS = [
    "eleconomista.es",
    "elpais.com",
    "abc.es",
    "expansion.com",
    "elmundo.es",
    "cincodias.elpais.com",
    "elconfidencial.com",
    "reuters.com",
    "bloomberg.com",
    "investing.com"
]
